services:
  zagle:
    image: ${ZAGLE_IMAGE}
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped
    networks:
      - nadprodukcje_default

networks:
  nadprodukcje_default:
    external: true
